# puts Gem::Specification.find_by_name('rubocop').full_gem_path + '/config/default.yml'
#   "/home/user/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.48.0/config/default.yml"
# https://raw.githubusercontent.com/rubocop/rubocop/master/config/default.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.1
  NewCops: enable

Naming/BlockForwarding:
  EnforcedStyle: explicit # default: anonymous
  # https://docs.rubocop.org/rubocop/cops_naming.html#namingblockforwarding

Layout/LineLength:
  Max: 120

#Layout/LineEndStringConcatenationIndentation:
#  EnforcedStyle: aligned # (default)
#  https://docs.rubocop.org/rubocop/cops_layout.html#layoutlineendstringconcatenationindentation

Layout/LineContinuationLeadingSpace:
  Enabled: false

Security/Eval:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20 # DEFAULT 10
Metrics/AbcSize:
  Max: 27 # DEFAULT 17
Metrics/CyclomaticComplexity:
  Max: 9 # DEFAULT 7
Metrics/PerceivedComplexity:
  Max: 9 # DEFAULT 8
Metrics/ClassLength:
  Max: 125 # DEFAULT 100

#Lint/RedundantStringCoercion:
#  Enabled: false
# ...256/mailanes/blob/master/.rubocop.yml
#       /total/blob/master/.rubocop.yml
#Layout/EmptyLineAfterGuardClause:
#  Enabled: false
#Layout/MultilineMethodCallIndentation:
#  Enabled: false
#Metrics/AbcSize:
#  Max: 50
#Metrics/CyclomaticComplexity:
#  Max: 10
#Metrics/PerceivedComplexity:
#  Max: 10
#Metrics/ParameterLists:
#  Max: 10
#Layout/AlignParameters:
#  Enabled: false
